services:
  app:
    build: .
    ports:
      - '5040:8080'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${PGPORT}
      DATABASE_USER: ${PGUSER}
      DATABASE_PASSWORD: ${PGPASSWORD}
      DATABASE_NAME: ${PGDATABASE}

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: